# Generated by Django 4.2.1 on 2023-06-08 20:18

from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to=products.models.get_product_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datasheet', models.FileField(blank=True, null=True, upload_to=products.models.get_product_datasheet_path)),
                ('model', models.CharField(blank=True, max_length=256, null=True)),
                ('product_warranty', models.CharField(blank=True, max_length=256, null=True)),
                ('maximum_power', models.CharField(blank=True, max_length=256, null=True)),
                ('voltage_at_maximum_power', models.CharField(blank=True, max_length=256, null=True)),
                ('current_at_maximum_power', models.CharField(blank=True, max_length=256, null=True)),
                ('open_circuit_voltage', models.CharField(blank=True, max_length=256, null=True)),
                ('short_circuit_current', models.CharField(blank=True, max_length=256, null=True)),
                ('panel_efficiency', models.CharField(blank=True, max_length=256, null=True)),
                ('maximum_system_voltage', models.CharField(blank=True, max_length=256, null=True)),
                ('series_fuse_rating', models.CharField(blank=True, max_length=256, null=True)),
                ('panel_dimensions', models.CharField(blank=True, max_length=256, null=True)),
                ('weight', models.CharField(blank=True, max_length=256, null=True)),
                ('cell_type', models.CharField(blank=True, max_length=256, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=256, null=True)),
                ('frame_type', models.CharField(blank=True, max_length=256, null=True)),
                ('junction_box_diodes', models.CharField(blank=True, max_length=256, null=True)),
                ('junction_box_protection_class', models.CharField(blank=True, max_length=256, null=True)),
                ('connector_type', models.CharField(blank=True, max_length=256, null=True)),
                ('cable_crossection', models.CharField(blank=True, max_length=256, null=True)),
                ('cable_length', models.CharField(blank=True, max_length=256, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='products.product')),
            ],
        ),
    ]
